set(CMAKE_THIRD_PARTY_PATH "${CMAKE_CURRENT_LIST_DIR}/..")

set(MOCKCPP_PATH ${CMAKE_THIRD_PARTY_PATH}/mockcpp)
set(MOCKCPP_INC_PATH ${MOCKCPP_PATH}/include)
set(MOCKCPP_LIB_PATH ${MOCKCPP_PATH}/lib)

message(STATUS "MOCKCPP_INC_PATH:           ${MOCKCPP_INC_PATH}")
message(STATUS "MOCKCPP_LIB_PATH:           ${MOCKCPP_LIB_PATH}")
