set(CMAKE_THIRD_PARTY_PATH "${CMAKE_CURRENT_LIST_DIR}/..")
set(gtest_force_shared_crt ON CACHE BOOL "" FORCE)
set(GOOGLE_TEST_PATH ${CMAKE_THIRD_PARTY_PATH}/googletest)
set(GOOGLE_TEST_INC_PATH ${GOOGLE_TEST_PATH}/include)
set(GOOGLE_TEST_LIB_PATH ${GOOGLE_TEST_PATH}/lib)

message(STATUS "GOOGLE_TEST_INCLUDE_PATH:   ${GOOGLE_TEST_INC_PATH}")
message(STATUS "GOOGLE_TEST_LIBRARY_PATH:   ${GOOGLE_TEST_LIB_PATH}")
