set(CMAKE_THIRD_PARTY_PATH "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)

set(UTILS_PATH ${CMAKE_THIRD_PARTY_PATH}/utils)
set(UTILS_INC_PATH ${UTILS_PATH}/include)
set(UTILS_LIB_PATH ${UTILS_PATH}/lib)
set(UTILS_STATIC_LIB_NAME utils_static)
set(UTILS_SHARED_LIB_NAME utils_shared)

message(STATUS "UTILS_INC_PATH:           ${UTILS_INC_PATH}")
message(STATUS "UTILS_LIB_PATH:           ${UTILS_LIB_PATH}")
