set(CMAKE_THIRD_PARTY_PATH "${CMAKE_CURRENT_LIST_DIR}/..")

set(CJSON_PATH ${CMAKE_THIRD_PARTY_PATH}/cjson)
set(CJSON_INC_PATH ${CJSON_PATH}/include)
set(CJSON_LIB_PATH ${CJSON_PATH}/lib)

message(STATUS "CJSON_INC_PATH:           ${CJSON_INC_PATH}")
message(STATUS "CJSON_LIB_PATH:           ${CJSON_LIB_PATH}")
