include(ExternalProject)

set(CJSON_NAME cjson)
set(CJSON_PREFIX ${EXTERNAL_PREFIX_DIR}/${CJSON_NAME})
set(CJSON_SRC_DIR ${EXTERNAL_CODE_DIR}/${CJSON_NAME})
set(CJSON_BUILD_DIR ${EXTERNAL_BUILD_DIR}/${CJSON_NAME})
set(CJSON_INSTALL_DIR ${EXTERNAL_INSTALL_DIR}/${CJSON_NAME})
set(CJSON_STAMP_DIR ${EXTERNAL_STAMP_DIR}/${CJSON_NAME})

if (EXISTS ${CJSON_SRC_DIR})
    ExternalProject_Add(
        ${CJSON_NAME}

        SOURCE_DIR ${CJSON_SRC_DIR}
        BINARY_DIR ${CJSON_BUILD_DIR}
        STAMP_DIR ${CJSON_STAMP_DIR}
        UPDATE_COMMAND ""
        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${CJSON_INSTALL_DIR}
            -DCMAKE_GENERATOR=${CMAKE_GENERATOR}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            -DCMAKE_POLICY_VERSION_MINIMUM=3.10
            -DENABLE_CJSON_TEST=OFF
            -DENABLE_CUSTOM_COMPILER_FLAGS=OFF
    )
else()
    ExternalProject_Add(
        ${CJSON_NAME}
        GIT_REPOSITORY https://github.com/DaveGamble/cJSON.git
        GIT_TAG  v1.7.15
        PREFIX ${CJSON_PREFIX}
        SOURCE_DIR ${CJSON_SRC_DIR}
        BINARY_DIR ${CJSON_BUILD_DIR}
        STAMP_DIR ${CJSON_STAMP_DIR}
        UPDATE_COMMAND ""
        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${CJSON_INSTALL_DIR}
            -DCMAKE_GENERATOR=${CMAKE_GENERATOR}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            -DCMAKE_POLICY_VERSION_MINIMUM=3.10
            -DENABLE_CJSON_TEST=OFF
            -DENABLE_CUSTOM_COMPILER_FLAGS=OFF
    )
endif()
