include(ExternalProject)

set(GTEST_NAME googletest)
set(GTEST_PREFIX ${EXTERNAL_PREFIX_DIR}/${GTEST_NAME})
set(GTEST_SRC_DIR ${EXTERNAL_CODE_DIR}/${GTEST_NAME})
set(GTEST_BUILD_DIR ${EXTERNAL_BUILD_DIR}/${GTEST_NAME})
set(GTEST_INSTALL_DIR ${EXTERNAL_INSTALL_DIR}/${GTEST_NAME})
set(GTEST_STAMP_DIR ${EXTERNAL_STAMP_DIR}/${GTEST_NAME})

ExternalProject_Add(
    ${GTEST_NAME}
    GIT_REPOSITORY https://github.com/google/googletest.git
    GIT_TAG release-1.12.1
    PREFIX ${GTEST_PREFIX}
    SOURCE_DIR ${GTEST_SRC_DIR}
    BINARY_DIR ${GTEST_BUILD_DIR}
    STAMP_DIR ${GTEST_STAMP_DIR}
    UPDATE_COMMAND ""
    CMAKE_ARGS
        -DCMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}/${GTEST_NAME}
        -DCMAKE_GENERATOR=${CMAKE_GENERATOR}
        -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        -DCMAKE_POLICY_VERSION_MINIMUM=3.10
)
