include(ExternalProject)

set(GTEST_NAME googletest)

set(GTEST_PREFIX_DIR    ${EXTERNAL_PREFIX_DIR}/${GTEST_NAME})
set(GTEST_SRC_DIR       ${EXTERNAL_CODE_DIR}/${GTEST_NAME})
set(GTEST_BUILD_DIR     ${EXTERNAL_BUILD_DIR}/${GTEST_NAME})
set(GTEST_INSTALL_DIR   ${EXTERNAL_INSTALL_DIR}/${GTEST_NAME})
set(GTEST_STAMP_DIR     ${EXTERNAL_STAMP_DIR}/${GTEST_NAME})

set(GTEST_GIT_URL "https://github.com/google/googletest.git")
set(GTEST_GIT_TAG "release-1.12.1")

set(GTEST_CONFIG_FILE ${EXTERNAL_CONFIG_SOURCE_DIR}/${GTEST_NAME}.cmake)
set(GTEST_INSTALL_FILE ${GTEST_NAME}.cmake)
install(FILES ${GTEST_CONFIG_FILE}
        DESTINATION ${EXTERNAL_CONFIG_INSTALL_DIR}
        RENAME ${GTEST_INSTALL_FILE})

if (EXISTS ${GTEST_SRC_DIR})
    ExternalProject_Add(
        ${GTEST_NAME}

        PREFIX      ${GTEST_PREFIX_DIR}
        SOURCE_DIR  ${GTEST_SRC_DIR}
        BINARY_DIR  ${GTEST_BUILD_DIR}
        STAMP_DIR   ${GTEST_STAMP_DIR}

        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${GTEST_INSTALL_DIR}
            -DCMAKE_GENERATOR=${CMAKE_GENERATOR}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            -DCMAKE_POLICY_VERSION_MINIMUM=3.10
    )
else()
    ExternalProject_Add(
        ${GTEST_NAME}

        GIT_REPOSITORY  ${GTEST_GIT_URL}
        GIT_TAG         ${GTEST_GIT_TAG}

        PREFIX          ${GTEST_PREFIX_DIR}
        SOURCE_DIR      ${GTEST_SRC_DIR}
        BINARY_DIR      ${GTEST_BUILD_DIR}
        STAMP_DIR       ${GTEST_STAMP_DIR}

        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${GTEST_INSTALL_DIR}
            -DCMAKE_GENERATOR=${CMAKE_GENERATOR}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            -DCMAKE_POLICY_VERSION_MINIMUM=3.10

        UPDATE_COMMAND ""
    )
endif()
