include(ExternalProject)

set(UTILS_NAME utils)
set(UTILS_PREFIX ${EXTERNAL_PREFIX_DIR}/${UTILS_NAME})
set(UTILS_SRC_DIR ${EXTERNAL_CODE_DIR}/${UTILS_NAME})
set(UTILS_BUILD_DIR ${EXTERNAL_BUILD_DIR}/${UTILS_NAME})
set(UTILS_INSTALL_DIR ${EXTERNAL_INSTALL_DIR}/${UTILS_NAME})
set(UTILS_STAMP_DIR ${EXTERNAL_STAMP_DIR}/${UTILS_NAME})

if (EXISTS ${UTILS_SRC_DIR})
    ExternalProject_Add(
        ${UTILS_NAME}

        SOURCE_DIR ${UTILS_SRC_DIR}
        BINARY_DIR ${UTILS_BUILD_DIR}
        STAMP_DIR ${UTILS_STAMP_DIR}
        UPDATE_COMMAND ""
        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${UTILS_INSTALL_DIR}
            -DCMAKE_GENERATOR=${CMAKE_GENERATOR}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
    )
else()
    ExternalProject_Add(
        ${UTILS_NAME}
        GIT_REPOSITORY https://github.com/LeeYoungCN/utils.git
        GIT_TAG  master
        PREFIX ${UTILS_PREFIX}
        SOURCE_DIR ${UTILS_SRC_DIR}
        BINARY_DIR ${UTILS_BUILD_DIR}
        STAMP_DIR ${UTILS_STAMP_DIR}
        UPDATE_COMMAND ""
        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${UTILS_INSTALL_DIR}
            -DCMAKE_GENERATOR=${CMAKE_GENERATOR}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
    )
endif()
