include(ExternalProject)

set(UTILS_NAME utils)

set(UTILS_PREFIX_DIR    ${EXTERNAL_PREFIX_DIR}/${UTILS_NAME})
set(UTILS_SRC_DIR       ${EXTERNAL_CODE_DIR}/${UTILS_NAME})
set(UTILS_BUILD_DIR     ${EXTERNAL_BUILD_DIR}/${UTILS_NAME})
set(UTILS_INSTALL_DIR   ${EXTERNAL_INSTALL_DIR}/${UTILS_NAME})
set(UTILS_STAMP_DIR     ${EXTERNAL_STAMP_DIR}/${UTILS_NAME})

set(UTILS_GIT_URL "https://github.com/LeeYoungCN/utils.git")
set(UTILS_GIT_TAG "master")

set(UTILS_CONFIG_FILE ${EXTERNAL_CONFIG_SOURCE_DIR}/${UTILS_NAME}.cmake)
set(UTILS_INSTALL_FILE ${UTILS_NAME}.cmake)

install(FILES ${UTILS_CONFIG_FILE}
        DESTINATION ${EXTERNAL_CONFIG_INSTALL_DIR}
        RENAME ${UTILS_INSTALL_FILE})

if (EXISTS ${UTILS_SRC_DIR})
    ExternalProject_Add(
        ${UTILS_NAME}

        PREFIX ${UTILS_PREFIX_DIR}
        SOURCE_DIR ${UTILS_SRC_DIR}
        BINARY_DIR ${UTILS_BUILD_DIR}
        STAMP_DIR ${UTILS_STAMP_DIR}

        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${UTILS_INSTALL_DIR}
            -DCMAKE_GENERATOR=${CMAKE_GENERATOR}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
            -DCMAKE_PRESET=${CMAKE_PRESET}
    )
else()
    ExternalProject_Add(
        ${UTILS_NAME}

        GIT_REPOSITORY  ${UTILS_GIT_URL}
        GIT_TAG         ${UTILS_GIT_TAG}

        PREFIX          ${UTILS_PREFIX_DIR}
        SOURCE_DIR      ${UTILS_SRC_DIR}
        BINARY_DIR      ${UTILS_BUILD_DIR}
        STAMP_DIR       ${UTILS_STAMP_DIR}

        CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${UTILS_INSTALL_DIR}
            -DCMAKE_GENERATOR=${CMAKE_GENERATOR}
            -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
            -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
            -DCMAKE_PRESET=${CMAKE_PRESET}

        UPDATE_COMMAND ""
    )
endif()
