set(CMAKE_THIRD_PARTY_PATH "${CMAKE_CURRENT_LIST_DIR}/..")

set(UTILS_PATH ${CMAKE_THIRD_PARTY_PATH}/utils)
set(UTILS_INC_PATH ${UTILS_PATH}/include)
set(UTILS_LIB_PATH ${UTILS_PATH}/lib)

message(STATUS "UTILS_INC_PATH:           ${UTILS_INC_PATH}")
message(STATUS "UTILS_LIB_PATH:           ${UTILS_LIB_PATH}")
